//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudianteImage.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class tblEstudiante
    {
        public int EstudianteId { get; set; }

		[Required(ErrorMessage ="El Nombre es obligatorio")]
        public string Nombre { get; set; }

		[Required(ErrorMessage = "El Apellido es obligatorio")]
		public string Apellido { get; set; }

		[Required(ErrorMessage = "La Direccion es obligatorio")]
		public string Direccion { get; set; }

		[Required(ErrorMessage = "El Teléfono es obligatorio")]
		[MaxLength(10, ErrorMessage = "Ingrese un Teléfono Válido")]
		public string Telefono { get; set; }

		[Required(ErrorMessage = "El Cédula es obligatorio")]
		[MaxLength(11, ErrorMessage = "Ingrese una Cédula Válida")]
		public string Cedula { get; set; }

		[Required(ErrorMessage = "La Imagen es obligatorio")]
		public string ImageUrl { get; set; }
    }
}
